apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: frontend
    version: v2
  name: rs-nginx557
  namespace: frontend-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      containers:
      - env:
        image: nginxXXXXXXX
        imagePullPolicy: IfNotPresent
        name: nginx
